### ISSUE TITLE
Add sample MVVM implementation

### ISSUE THREAD

**Issue by nikhilbansal97** [nikhilbansal97/SampleMVP#1]
Add sample MVVM implementation in a new Branch with Readme

**Comment by aoudiamoncef** [comment]
Hello, i tried to implement a MVVM version of the application. Feel free to improve the Readme. Thanks

**Comment by nikhilbansal97** [comment]
@Sparow199 Awesome! Can you update the PR to merge in the `mvvm` branch I just created. I wanted to keep both samples separately..
